[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_version = "20"
  included_files = ["public/**"]
